CREATE TABLE list (
    id INT AUTO_INCREMENT PRIMARY KEY,
    list VARCHAR(255) NOT NULL
);

CREATE TABLE item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item VARCHAR(255) NOT NULL,
    list INT NOT NULL,
    FOREIGN KEY (list) REFERENCES list (id)
);
