version: '3.3'

services:
  db:
    build:
      context: ..
      dockerfile: ./database/Dockerfile.db
    container_name: db
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: flaskini
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_INITDB_SKIP_TZINFO: 1
  sonar:
    build:
      context: ..
      dockerfile: ./sonar/Dockerfile.sonar
    container_name: sonar
    ports:
      - 9001:9000
